# site settings:
title: Citizens Advice Design System
url: "https://citizensadvice.github.io/ca-designsystem/"
baseurl: ""

# build settings:
source: "src"
current_version: 0.0.1
docs_version: 1.0
markdown: kramdown
highlighter: rouge