# Site settings
title: Your awesome title
email: your-email@example.com
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
current_version: 0.1.0
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
sass:
  sass_dir: assets/css

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
