# site settings:
title: Citizens Advice Design System
url: "https://citizensadvice.github.io/cads"
github_url: "https://github.com/citizensadvice/cads"

# build settings:
framework_version: 0.0.5
docs_version: 1.0
