# Site settings
title: Citizens Advice Design System
baseurl: "/ca-designsystem"
url: https://btomy.github.io/ca-designsystem
production_url : https://btomy.github.io/ca-designsystem

# Build settings
source: "site"
current_version: 0.1.0
docs_version: 1.0
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# sass:
#   sass_dir: docs/1.0/assets/scss

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
