version: "3"

services:
  cads:
    volumes:
      - .:/cads
      - cads-node_modules:/cads/node_modules
      - cads-jekyll_website:/cads/website/_site
      - cads-website_sass_cache:/cads/website/.sass-cache
      - cads-jekyll_sandbox:/cads/sandbox/_site
      - cads-sandbox_sass_cache:/cads/sandbox/.sass-cache
    user: root
    env_file:
      - ./docker/dev.env

  cads-website:
    volumes:
      - .:/cads
      - cads-node_modules:/cads/node_modules
      - cads-jekyll_website:/cads/website/_site
      - cads-website_sass_cache:/cads/website/.sass-cache
    user: root
    env_file:
      - ./docker/dev.env

  cads-sandbox:
    volumes:
      - .:/cads
      - cads-node_modules:/cads/node_modules
      - cads-jekyll_sandbox:/cads/sandbox/_site
      - cads-sandbox_sass_cache:/cads/sandbox/.sass-cache
    user: root
    env_file:
      - ./docker/dev.env

  cads-watch:
    image: "cads${CADS_VERSION_TAG}"
    container_name: cads-watch.test
    labels:
      - "traefik.enable=false"
    command: yarn watchcss:all
    volumes:
      - .:/cads
      - cads-node_modules:/cads/node_modules
      - cads-jekyll_website:/cads/website/_site
      - cads-website_sass_cache:/cads/website/.sass-cache
      - cads-jekyll_sandbox:/cads/sandbox/_site
      - cads-sandbox_sass_cache:/cads/sandbox/.sass-cache
    user: root
    env_file:
      - ./docker/dev.env

volumes:
  cads-node_modules: {}
  cads-jekyll_website: {}
  cads-website_sass_cache: {}
  cads-jekyll_sandbox: {}
  cads-sandbox_sass_cache: {}
