# site settings:
title: Citizens Advice Design System
url: "https://citizensadvice.github.io/cads"
github_url: "https://github.com/citizensadvice/cads"
baseurl: "/cads"
host: 0.0.0.0

# build settings:
source: "src"
framework_version: 0.0.4
docs_version: 1.0
markdown: kramdown
highlighter: rouge
