# Site settings
title: Citizens Advice Design System
baseurl: "/cads"
url: https://btomy.github.io/cads
production_url: https://btomy.github.io/cads

# Build settings
source: "website"
current_version: 0.0.1
docs_version: 0.0.1
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
